/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    services: Service;
    media: Media;
    cities: City;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        enableIcon?: boolean | null;
        icon?: {
          name?:
            | (
                | 'AcademicCapIcon'
                | 'AdjustmentsHorizontalIcon'
                | 'AdjustmentsVerticalIcon'
                | 'ArchiveBoxArrowDownIcon'
                | 'ArchiveBoxIcon'
                | 'ArchiveBoxXMarkIcon'
                | 'ArrowDownCircleIcon'
                | 'ArrowDownIcon'
                | 'ArrowDownLeftIcon'
                | 'ArrowDownOnSquareIcon'
                | 'ArrowDownOnSquareStackIcon'
                | 'ArrowDownRightIcon'
                | 'ArrowDownTrayIcon'
                | 'ArrowLeftCircleIcon'
                | 'ArrowLeftEndOnRectangleIcon'
                | 'ArrowLeftIcon'
                | 'ArrowLeftOnRectangleIcon'
                | 'ArrowLeftStartOnRectangleIcon'
                | 'ArrowLongDownIcon'
                | 'ArrowLongLeftIcon'
                | 'ArrowLongRightIcon'
                | 'ArrowLongUpIcon'
                | 'ArrowPathIcon'
                | 'ArrowPathRoundedSquareIcon'
                | 'ArrowRightCircleIcon'
                | 'ArrowRightEndOnRectangleIcon'
                | 'ArrowRightIcon'
                | 'ArrowRightOnRectangleIcon'
                | 'ArrowRightStartOnRectangleIcon'
                | 'ArrowSmallDownIcon'
                | 'ArrowSmallLeftIcon'
                | 'ArrowSmallRightIcon'
                | 'ArrowSmallUpIcon'
                | 'ArrowTopRightOnSquareIcon'
                | 'ArrowTrendingDownIcon'
                | 'ArrowTrendingUpIcon'
                | 'ArrowTurnDownLeftIcon'
                | 'ArrowTurnDownRightIcon'
                | 'ArrowTurnLeftDownIcon'
                | 'ArrowTurnLeftUpIcon'
                | 'ArrowTurnRightDownIcon'
                | 'ArrowTurnRightUpIcon'
                | 'ArrowTurnUpLeftIcon'
                | 'ArrowTurnUpRightIcon'
                | 'ArrowUpCircleIcon'
                | 'ArrowUpIcon'
                | 'ArrowUpLeftIcon'
                | 'ArrowUpOnSquareIcon'
                | 'ArrowUpOnSquareStackIcon'
                | 'ArrowUpRightIcon'
                | 'ArrowUpTrayIcon'
                | 'ArrowUturnDownIcon'
                | 'ArrowUturnLeftIcon'
                | 'ArrowUturnRightIcon'
                | 'ArrowUturnUpIcon'
                | 'ArrowsPointingInIcon'
                | 'ArrowsPointingOutIcon'
                | 'ArrowsRightLeftIcon'
                | 'ArrowsUpDownIcon'
                | 'AtSymbolIcon'
                | 'BackspaceIcon'
                | 'BackwardIcon'
                | 'BanknotesIcon'
                | 'Bars2Icon'
                | 'Bars3BottomLeftIcon'
                | 'Bars3BottomRightIcon'
                | 'Bars3CenterLeftIcon'
                | 'Bars3Icon'
                | 'Bars4Icon'
                | 'BarsArrowDownIcon'
                | 'BarsArrowUpIcon'
                | 'Battery0Icon'
                | 'Battery100Icon'
                | 'Battery50Icon'
                | 'BeakerIcon'
                | 'BellAlertIcon'
                | 'BellIcon'
                | 'BellSlashIcon'
                | 'BellSnoozeIcon'
                | 'BoldIcon'
                | 'BoltIcon'
                | 'BoltSlashIcon'
                | 'BookOpenIcon'
                | 'BookmarkIcon'
                | 'BookmarkSlashIcon'
                | 'BookmarkSquareIcon'
                | 'BriefcaseIcon'
                | 'BugAntIcon'
                | 'BuildingLibraryIcon'
                | 'BuildingOffice2Icon'
                | 'BuildingOfficeIcon'
                | 'BuildingStorefrontIcon'
                | 'CakeIcon'
                | 'CalculatorIcon'
                | 'CalendarDateRangeIcon'
                | 'CalendarDaysIcon'
                | 'CalendarIcon'
                | 'CameraIcon'
                | 'ChartBarIcon'
                | 'ChartBarSquareIcon'
                | 'ChartPieIcon'
                | 'ChatBubbleBottomCenterIcon'
                | 'ChatBubbleBottomCenterTextIcon'
                | 'ChatBubbleLeftEllipsisIcon'
                | 'ChatBubbleLeftIcon'
                | 'ChatBubbleLeftRightIcon'
                | 'ChatBubbleOvalLeftEllipsisIcon'
                | 'ChatBubbleOvalLeftIcon'
                | 'CheckBadgeIcon'
                | 'CheckCircleIcon'
                | 'CheckIcon'
                | 'ChevronDoubleDownIcon'
                | 'ChevronDoubleLeftIcon'
                | 'ChevronDoubleRightIcon'
                | 'ChevronDoubleUpIcon'
                | 'ChevronDownIcon'
                | 'ChevronLeftIcon'
                | 'ChevronRightIcon'
                | 'ChevronUpDownIcon'
                | 'ChevronUpIcon'
                | 'CircleStackIcon'
                | 'ClipboardDocumentCheckIcon'
                | 'ClipboardDocumentIcon'
                | 'ClipboardDocumentListIcon'
                | 'ClipboardIcon'
                | 'ClockIcon'
                | 'CloudArrowDownIcon'
                | 'CloudArrowUpIcon'
                | 'CloudIcon'
                | 'CodeBracketIcon'
                | 'CodeBracketSquareIcon'
                | 'Cog6ToothIcon'
                | 'Cog8ToothIcon'
                | 'CogIcon'
                | 'CommandLineIcon'
                | 'ComputerDesktopIcon'
                | 'CpuChipIcon'
                | 'CreditCardIcon'
                | 'CubeIcon'
                | 'CubeTransparentIcon'
                | 'CurrencyBangladeshiIcon'
                | 'CurrencyDollarIcon'
                | 'CurrencyEuroIcon'
                | 'CurrencyPoundIcon'
                | 'CurrencyRupeeIcon'
                | 'CurrencyYenIcon'
                | 'CursorArrowRaysIcon'
                | 'CursorArrowRippleIcon'
                | 'DevicePhoneMobileIcon'
                | 'DeviceTabletIcon'
                | 'DivideIcon'
                | 'DocumentArrowDownIcon'
                | 'DocumentArrowUpIcon'
                | 'DocumentChartBarIcon'
                | 'DocumentCheckIcon'
                | 'DocumentCurrencyBangladeshiIcon'
                | 'DocumentCurrencyDollarIcon'
                | 'DocumentCurrencyEuroIcon'
                | 'DocumentCurrencyPoundIcon'
                | 'DocumentCurrencyRupeeIcon'
                | 'DocumentCurrencyYenIcon'
                | 'DocumentDuplicateIcon'
                | 'DocumentIcon'
                | 'DocumentMagnifyingGlassIcon'
                | 'DocumentMinusIcon'
                | 'DocumentPlusIcon'
                | 'DocumentTextIcon'
                | 'EllipsisHorizontalCircleIcon'
                | 'EllipsisHorizontalIcon'
                | 'EllipsisVerticalIcon'
                | 'EnvelopeIcon'
                | 'EnvelopeOpenIcon'
                | 'EqualsIcon'
                | 'ExclamationCircleIcon'
                | 'ExclamationTriangleIcon'
                | 'EyeDropperIcon'
                | 'EyeIcon'
                | 'EyeSlashIcon'
                | 'FaceFrownIcon'
                | 'FaceSmileIcon'
                | 'FilmIcon'
                | 'FingerPrintIcon'
                | 'FireIcon'
                | 'FlagIcon'
                | 'FolderArrowDownIcon'
                | 'FolderIcon'
                | 'FolderMinusIcon'
                | 'FolderOpenIcon'
                | 'FolderPlusIcon'
                | 'ForwardIcon'
                | 'FunnelIcon'
                | 'GifIcon'
                | 'GiftIcon'
                | 'GiftTopIcon'
                | 'GlobeAltIcon'
                | 'GlobeAmericasIcon'
                | 'GlobeAsiaAustraliaIcon'
                | 'GlobeEuropeAfricaIcon'
                | 'H1Icon'
                | 'H2Icon'
                | 'H3Icon'
                | 'HandRaisedIcon'
                | 'HandThumbDownIcon'
                | 'HandThumbUpIcon'
                | 'HashtagIcon'
                | 'HeartIcon'
                | 'HomeIcon'
                | 'HomeModernIcon'
                | 'IdentificationIcon'
                | 'InboxArrowDownIcon'
                | 'InboxIcon'
                | 'InboxStackIcon'
                | 'InformationCircleIcon'
                | 'ItalicIcon'
                | 'KeyIcon'
                | 'LanguageIcon'
                | 'LifebuoyIcon'
                | 'LightBulbIcon'
                | 'LinkIcon'
                | 'LinkSlashIcon'
                | 'ListBulletIcon'
                | 'LockClosedIcon'
                | 'LockOpenIcon'
                | 'MagnifyingGlassCircleIcon'
                | 'MagnifyingGlassIcon'
                | 'MagnifyingGlassMinusIcon'
                | 'MagnifyingGlassPlusIcon'
                | 'MapIcon'
                | 'MapPinIcon'
                | 'MegaphoneIcon'
                | 'MicrophoneIcon'
                | 'MinusCircleIcon'
                | 'MinusIcon'
                | 'MinusSmallIcon'
                | 'MoonIcon'
                | 'MusicalNoteIcon'
                | 'NewspaperIcon'
                | 'NoSymbolIcon'
                | 'NumberedListIcon'
                | 'PaintBrushIcon'
                | 'PaperAirplaneIcon'
                | 'PaperClipIcon'
                | 'PauseCircleIcon'
                | 'PauseIcon'
                | 'PencilIcon'
                | 'PencilSquareIcon'
                | 'PercentBadgeIcon'
                | 'PhoneArrowDownLeftIcon'
                | 'PhoneArrowUpRightIcon'
                | 'PhoneIcon'
                | 'PhoneXMarkIcon'
                | 'PhotoIcon'
                | 'PlayCircleIcon'
                | 'PlayIcon'
                | 'PlayPauseIcon'
                | 'PlusCircleIcon'
                | 'PlusIcon'
                | 'PlusSmallIcon'
                | 'PowerIcon'
                | 'PresentationChartBarIcon'
                | 'PresentationChartLineIcon'
                | 'PrinterIcon'
                | 'PuzzlePieceIcon'
                | 'QrCodeIcon'
                | 'QuestionMarkCircleIcon'
                | 'QueueListIcon'
                | 'RadioIcon'
                | 'ReceiptPercentIcon'
                | 'ReceiptRefundIcon'
                | 'RectangleGroupIcon'
                | 'RectangleStackIcon'
                | 'RocketLaunchIcon'
                | 'RssIcon'
                | 'ScaleIcon'
                | 'ScissorsIcon'
                | 'ServerIcon'
                | 'ServerStackIcon'
                | 'ShareIcon'
                | 'ShieldCheckIcon'
                | 'ShieldExclamationIcon'
                | 'ShoppingBagIcon'
                | 'ShoppingCartIcon'
                | 'SignalIcon'
                | 'SignalSlashIcon'
                | 'SlashIcon'
                | 'SparklesIcon'
                | 'SpeakerWaveIcon'
                | 'SpeakerXMarkIcon'
                | 'Square2StackIcon'
                | 'Square3Stack3DIcon'
                | 'Squares2X2Icon'
                | 'SquaresPlusIcon'
                | 'StarIcon'
                | 'StopCircleIcon'
                | 'StopIcon'
                | 'StrikethroughIcon'
                | 'SunIcon'
                | 'SwatchIcon'
                | 'TableCellsIcon'
                | 'TagIcon'
                | 'TicketIcon'
                | 'TrashIcon'
                | 'TrophyIcon'
                | 'TruckIcon'
                | 'TvIcon'
                | 'UnderlineIcon'
                | 'UserCircleIcon'
                | 'UserGroupIcon'
                | 'UserIcon'
                | 'UserMinusIcon'
                | 'UserPlusIcon'
                | 'UsersIcon'
                | 'VariableIcon'
                | 'VideoCameraIcon'
                | 'VideoCameraSlashIcon'
                | 'ViewColumnsIcon'
                | 'ViewfinderCircleIcon'
                | 'WalletIcon'
                | 'WifiIcon'
                | 'WindowIcon'
                | 'WrenchIcon'
                | 'WrenchScrewdriverIcon'
                | 'XCircleIcon'
                | 'XMarkIcon'
              )
            | null;
          size?: ('sm' | 'md' | 'lg') | null;
          color?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  position?: ('default' | 'fullscreen') | null;
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'services' | null;
  categories?: (string | Category)[] | null;
  locations?: (string | City)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'services';
        value: string | Service;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  'city name': string;
  country: string;
  'display name': string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  summary: string;
  city: (string | City)[];
  listedOn?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  categories?: (string | null) | Category;
  slug?: string | null;
  slugLock?: boolean | null;
  skipSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}